version: '3'

x-python-test: &python-test
  working_dir: /app
  command: sh etc/container-test.sh
  volumes:
    - .:/app
    - pip-cache:/home/test/.cache/pip
  profiles:
    - tests

x-postgres-env:
  - &pghost
    PGHOST=postgres
  - &pguser
    PGUSER=postgres

x-mariadb-env:
  - &mariadbhost
    MYSQL_HOST=mariadb
  - &mariadbuser
    MYSQL_USER=root
  - &mariadbpassword
    MYSQL_PASSWORD=test

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - services

  mariadb:
    image: mariadb/server
    environment:
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
      - MARIADB_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/var/lib/mysql
    profiles:
      - services

  python-3.11:
    <<: *python-test
    image: pluca-test:3.11
    build:
      context: ./etc/docker
      args:
        PYTHON_VERSION: '3.11'
    environment:
      - PGDATABASE=python3_11
      - MYSQL_DATABASE=python3_11
      - *pghost
      - *pguser
      - *mariadbhost
      - *mariadbuser
      - *mariadbpassword

volumes:
  pip-cache:
  mariadb_data:
  postgres_data:
