[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = "3.7"

files = ["pluca", "tests"]
show_error_codes = true
strict = true

[[tool.mypy.overrides]]
module = [
       "setuptools",
       "appdirs"
       ]
ignore_missing_imports = true

[tool.taskipy.tasks]
test = "python -m doctest README.md && python -m unittest tests/test_*.py"
lint = "flake8 && mypy && pylint --jobs=0 pluca"
pre-commit = "task lint"
pre-push = "task lint && task test"
