[tool.poetry]
name = "pluca"
version = "0.1.0"
description = "Pluggable cache architecture for Python"
authors = ["Flávio Veloso <flaviovs@magnux.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.1"
mypy = "^0.812"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools!=50"]
build-backend = "poetry.core.masonry.api"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
